### ISSUE TITLE
staff.ecommerceberlin - any update needed?

### ISSUE THREAD

**Issue by az** [ecommerceberlin/staff.ecommerceberlin.com#23]
do u need some more info from the database?

like the aggregate number of furniture or so?

> btw: i saw that this page works very slowly on tablets...i think it it good idea to remove the list and show only results of filtering or search by query

![21  Targi eHandlu - Warszawa - 14 kwietnia 2022 2022-04-29 14-10-09](https://user-images.githubusercontent.com/2198/165941749-4fdbace6-1bfc-48cf-82bb-399cce73a5a6.jpg)

**Comment by jprzybylski4** [comment]
I believe it will be hard to have an aggregate number of furniture as we have a different standard for 9 and 18sqm:

- 1 table 2 chairs for 9 sqm
- 2 tables 4 chairs for 18sqm

> i think it is good idea to remove the list and show only results of filtering or search by query
I believe the full list was useful only for the welcome packs - now the filter/search view should be enough for us.

**Comment by az** [comment]
the best way is always a standardisation but in this case it is still doable ... just use the STD as the base and **add discounted furniture to 0 to grand, premium grand.** - let me know if you want to and will handle that this way and i should handle the aggregation

**Comment by jprzybylski4** [comment]
Ok, I'm starting to work on it now. I'll add missing 2 chairs and 1 table and discount them to 0 in the admin.

**Comment by jprzybylski4** [comment]
Done. All 18sqms that should have additional furniture have the upgrades added.

**Comment by az** [comment]
@jprzybylski4 thx. i will update staff.* soon...
