### ISSUE TITLE
Show order details instead of company details

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/staff.ecommerceberlin.com#6]
Re - report.map

I guess it might also not be possible since it's booking map widget, but is there any chance we could show order details (ie carpet color) instead of company details?
![E-commerce Berlin Expo | Berlin | February, 2022 2021-10-25 16-02-21](https://user-images.githubusercontent.com/75311923/138710484-e0ad2b84-3ab1-4f31-8c35-18f94a761ff6.png)

**Comment by az** [comment]
> z takich rzeczy ktore chcialbym dodac do rozpiska zakupow firmy po kliknieciu na stoisko na mapce (czyli podmiana overlaya) 

yes, this now a simple copy of salesmap widget but i will try to INJECT other booth details and than i will try to display more useful information for "venue context"
**carpet color is a perfect example**
